# Generated by Django 5.2.8 on 2025-12-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='state',
            new_name='county',
        ),
        migrations.RemoveField(
            model_name='property',
            name='zip_code',
        ),
    ]
