# Generated by Django 5.2.8 on 2025-12-05 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='size_sqft',
        ),
    ]
